# -*- coding: utf-8 -*-
"""
Sky Rules 全量同步脚本
同步 workflows / rules 到 Windsurf、Antigravity/Gemini、Codex/Agents。

用法:
  python sync-workflows.py          # git 提交并同步全部
  python sync-workflows.py --no-git # 跳过 git，仅同步全部
  python sync-workflows.py --print-targets # 只打印本机解析到的同步目标
  python sync-workflows.py --doctor # 体检本机同步配置，不执行同步
  python sync-workflows.py --verify # 只验证各平台工作流伴随资源
  python sync-workflows.py --no-git --include-missing-targets # 预创建全部默认目标
  python sync-workflows.py --no-git --skip-rules-check # 跳过内置规则自检

同步目标默认使用各工具的用户目录约定；如果其他电脑目录不同，可通过
SKY_RULES_* 环境变量覆盖，详见 README。
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
HOME = Path.home().resolve()

GENERATED_BY_MARKER = "Generated by sky-rules sync-workflows.py"
SKY_WORKFLOW_DESCRIPTION_MARKER = "Use when the user wants this Sky workflow:"
SOURCE_WORKFLOW_EDIT_MARKER = "Edit the source workflow, then sync again."

SRC_WORKFLOWS = ROOT / "workflows"
SRC_RULES = ROOT / "rules"
RULES_MANIFEST = SRC_RULES / "rules-manifest.json"
CHECK_RULES_SCRIPT = ROOT / "scripts" / "check-rules.py"
PROJECT_CATALOG_FILE = ROOT / "project-catalog.json"
PROJECT_CONTEXT_WORKFLOW_STEM = "base.project-context"
SRC_SKILLS = ROOT / "skills"
CONFIG_TARGET_FILES = [ROOT / "sync-targets.json", ROOT / "sync-targets.local.json"]
LOCAL_CONFIG_FILE = HOME / ".sky-rules" / "local.json"
CONFIG_WARNINGS: list[str] = []


def as_list(value: object) -> list[str]:
    """将配置中的字符串或数组统一转换成字符串列表。"""
    if value is None:
        return []

    if isinstance(value, str):
        return [value]

    if isinstance(value, (list, tuple, set)):
        return [str(item) for item in value if str(item)]

    return [str(value)]


def update_local_source_config() -> None:
    """记录本机 sky-rules 源仓库路径，并保留其他本地配置。"""
    config: dict[str, object] = {}
    if LOCAL_CONFIG_FILE.exists():
        try:
            loaded_config = json.loads(LOCAL_CONFIG_FILE.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise ValueError(f"本机配置读取失败，请修正或删除 {LOCAL_CONFIG_FILE}: {error}") from error

        if not isinstance(loaded_config, dict):
            raise ValueError(f"本机配置必须是 JSON 对象: {LOCAL_CONFIG_FILE}")

        config = loaded_config

    paths = config.get("paths")
    if not isinstance(paths, dict):
        paths = {}

    paths["skyRulesRepo"] = str(ROOT)
    config.setdefault("version", 1)
    config["paths"] = paths

    LOCAL_CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    LOCAL_CONFIG_FILE.write_text(
        json.dumps(config, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"[本机配置] OK sky-rules 源仓库: {LOCAL_CONFIG_FILE}")


def resolve_path(value: str | Path, relative_base: Path = ROOT) -> Path:
    """解析支持环境变量、~、${ROOT}、${HOME} 的路径。"""
    text = str(value)
    text = text.replace("${ROOT}", str(ROOT)).replace("${HOME}", str(HOME))
    path = Path(os.path.expandvars(text)).expanduser()
    if not path.is_absolute():
        path = relative_base / path

    return path.resolve()


def get_env_path(name: str, default: Path) -> Path:
    """读取路径环境变量；未配置时使用默认目标。"""
    value = os.environ.get(name)
    if not value:
        return default

    return resolve_path(value)


def get_first_env_path(names: list[str], default: Path) -> Path:
    """按优先级读取多个路径环境变量。"""
    for name in names:
        value = os.environ.get(name)
        if value:
            return resolve_path(value)

    return default


def get_codex_skills_dir(default: Path) -> Path:
    """读取 Codex Skills 目录，兼容早期 Agents 环境变量。"""
    for name in ["SKY_RULES_CODEX_SKILLS_DIR", "SKY_RULES_AGENTS_SKILLS_DIR"]:
        value = os.environ.get(name)
        if value:
            return resolve_path(value)

    agents_home = os.environ.get("SKY_RULES_AGENTS_HOME")
    if agents_home:
        return resolve_path(agents_home) / "skills"

    return default


WINDSURF_HOME = get_env_path("SKY_RULES_WINDSURF_HOME", HOME / ".codeium" / "windsurf")
GEMINI_HOME = get_env_path("SKY_RULES_GEMINI_HOME", HOME / ".gemini")
CODEX_HOME = get_first_env_path(["SKY_RULES_CODEX_HOME", "CODEX_HOME"], HOME / ".codex")

WINDSURF_WORKFLOWS_DIR = get_env_path(
    "SKY_RULES_WINDSURF_WORKFLOWS_DIR",
    WINDSURF_HOME / "global_workflows",
)
WINDSURF_RULES_FILE = get_env_path(
    "SKY_RULES_WINDSURF_RULES_FILE",
    WINDSURF_HOME / "memories" / "global_rules.md",
)
GEMINI_WORKFLOWS_DIR = get_env_path(
    "SKY_RULES_GEMINI_WORKFLOWS_DIR",
    GEMINI_HOME / "antigravity" / "global_workflows",
)
GEMINI_RULES_FILE = get_env_path("SKY_RULES_GEMINI_RULES_FILE", GEMINI_HOME / "GEMINI.md")
CODEX_AGENTS_FILE = get_env_path("SKY_RULES_CODEX_AGENTS_FILE", CODEX_HOME / "AGENTS.md")
CODEX_SKILLS_DIR = get_codex_skills_dir(CODEX_HOME / "skills")

BUILTIN_SYNC_MAP = [
    {
        "name": "Windsurf 工作流",
        "src": SRC_WORKFLOWS,
        "dst": WINDSURF_WORKFLOWS_DIR,
        "mode": "mirror",
        "pattern": "*.md",
        "exclude": ["README.md"],
        "exact_env": ["SKY_RULES_WINDSURF_WORKFLOWS_DIR"],
        "base_env": ["SKY_RULES_WINDSURF_HOME"],
        "detect": WINDSURF_HOME,
    },
    {
        "name": "Antigravity 工作流",
        "src": SRC_WORKFLOWS,
        "dst": GEMINI_WORKFLOWS_DIR,
        "mode": "mirror",
        "pattern": "*.md",
        "exclude": ["README.md"],
        "exact_env": ["SKY_RULES_GEMINI_WORKFLOWS_DIR"],
        "base_env": ["SKY_RULES_GEMINI_HOME"],
        "detect": GEMINI_HOME / "antigravity",
    },
    {
        "name": "Antigravity 规则",
        "src": RULES_MANIFEST,
        "dst": GEMINI_RULES_FILE,
        "mode": "assembled_rules",
        "exact_env": ["SKY_RULES_GEMINI_RULES_FILE"],
        "base_env": ["SKY_RULES_GEMINI_HOME"],
        "detect": GEMINI_HOME,
    },
    {
        "name": "Windsurf 全局规则",
        "src": RULES_MANIFEST,
        "dst": WINDSURF_RULES_FILE,
        "mode": "assembled_rules",
        "exact_env": ["SKY_RULES_WINDSURF_RULES_FILE"],
        "base_env": ["SKY_RULES_WINDSURF_HOME"],
        "detect": WINDSURF_HOME,
    },
    {
        "name": "Codex 全局规则",
        "src": RULES_MANIFEST,
        "dst": CODEX_AGENTS_FILE,
        "mode": "codex_rules",
        "exact_env": ["SKY_RULES_CODEX_AGENTS_FILE"],
        "base_env": ["SKY_RULES_CODEX_HOME", "CODEX_HOME"],
        "detect": CODEX_HOME,
    },
    {
        "name": "Codex Skills",
        "src": SRC_WORKFLOWS,
        "dst": CODEX_SKILLS_DIR,
        "mode": "agents_skills",
        "pattern": "*.md",
        "exclude": ["README.md"],
        "exact_env": ["SKY_RULES_CODEX_SKILLS_DIR", "SKY_RULES_AGENTS_SKILLS_DIR"],
        "base_env": ["SKY_RULES_CODEX_HOME", "CODEX_HOME", "SKY_RULES_AGENTS_HOME"],
        "detect": CODEX_HOME,
    },
]


def get_config_source_path(value: object, config_path: Path) -> Path:
    """解析外部配置中的源路径，默认相对仓库根目录。"""
    if not value:
        raise ValueError(f"{config_path.name}: target.source 不能为空")

    return resolve_path(str(value), ROOT)


def get_config_target_path(item: dict[str, object], config_path: Path) -> Path:
    """解析外部配置中的目标路径，环境变量优先于默认 target。"""
    for env_name in as_list(item.get("target_env") or item.get("exact_env")):
        value = os.environ.get(env_name)
        if value:
            return resolve_path(value)

    target = item.get("target")
    if not target:
        raise ValueError(f"{config_path.name}: target.target 不能为空")

    return resolve_path(str(target), ROOT)


def is_file_mode(mode: str) -> bool:
    """判断同步模式是否输出到单文件。"""
    return mode in {"file", "assembled_rules", "codex_rules"}


def normalize_config_target(item: object, config_path: Path) -> dict[str, object]:
    """将外部 JSON target 规范化成脚本内部同步目标结构。"""
    if not isinstance(item, dict):
        raise ValueError(f"{config_path.name}: targets 必须是对象数组")

    mode = str(item.get("mode", "")).strip()
    if mode not in {"mirror", "file", "assembled_rules", "codex_rules", "agents_skills"}:
        raise ValueError(f"{config_path.name}: 不支持的 mode: {mode}")

    name = str(item.get("name", "")).strip()
    if not name:
        raise ValueError(f"{config_path.name}: target.name 不能为空")

    src = get_config_source_path(item.get("source"), config_path)
    dst = get_config_target_path(item, config_path)
    exact_env = as_list(item.get("target_env") or item.get("exact_env"))
    base_env = as_list(item.get("base_env"))

    if item.get("detect"):
        detect = resolve_path(str(item["detect"]), ROOT)
    elif is_file_mode(mode):
        detect = dst.parent
    else:
        detect = dst

    target: dict[str, object] = {
        "name": name,
        "src": src,
        "dst": dst,
        "mode": mode,
        "pattern": str(item.get("pattern", "*.md")),
        "exclude": as_list(item.get("exclude")),
        "exact_env": exact_env,
        "base_env": base_env,
        "detect": detect,
        "config": config_path.name,
    }

    return target


def load_config_targets() -> list[dict[str, object]]:
    """读取 sync-targets*.json 扩展同步目标配置。"""
    targets: list[dict[str, object]] = []
    for config_path in CONFIG_TARGET_FILES:
        if not config_path.exists():
            continue

        try:
            raw_config = json.loads(config_path.read_text(encoding="utf-8"))
            raw_targets = raw_config.get("targets", raw_config) if isinstance(raw_config, dict) else raw_config
            if not isinstance(raw_targets, list):
                raise ValueError("根节点必须是数组，或包含 targets 数组")

            for raw_target in raw_targets:
                targets.append(normalize_config_target(raw_target, config_path))
        except (OSError, json.JSONDecodeError, ValueError) as error:
            CONFIG_WARNINGS.append(f"{config_path.name}: {error}")

    return targets


SYNC_MAP = [*BUILTIN_SYNC_MAP, *load_config_targets()]


def run_rules_check(stage: str, source_only: bool = False) -> None:
    """运行规则仓库自检，失败时阻断同步流程。"""
    if not CHECK_RULES_SCRIPT.exists():
        raise SystemExit(f"规则自检脚本不存在: {CHECK_RULES_SCRIPT}")

    command = [sys.executable, str(CHECK_RULES_SCRIPT)]
    if source_only:
        command.append("--source-only")

    print(f"[规则自检 - {stage}]", flush=True)
    result = subprocess.run(command, cwd=ROOT)
    if result.returncode != 0:
        raise SystemExit(f"规则自检失败，已停止同步（阶段：{stage}）")
    print()


def git_commit_and_push() -> None:
    """自动提交并推送 sky-rules 仓库变更。"""
    print("[1/2] Git 提交变更...")
    os.chdir(ROOT)

    subprocess.run(["git", "add", "-A"], check=True, capture_output=True)

    result = subprocess.run(["git", "diff", "--cached", "--quiet"], capture_output=True)
    if result.returncode != 0:
        subprocess.run(
            ["git", "commit", "-m", "update: sync workflows and rules"],
            check=True,
            capture_output=True,
        )
        push_result = subprocess.run(["git", "push"], capture_output=True, text=True)
        if push_result.returncode == 0:
            print("    OK: 已提交并推送")
        else:
            print("    WARN: 已提交，推送失败（可能无远程或网络问题）")
    else:
        print("    无变更需要提交")
    print()


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    text = text.lstrip("\ufeff")
    if not text.startswith("---"):
        return {}, text

    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text

    metadata: dict[str, str] = {}
    for line in parts[1].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip().strip('"').strip("'")
    return metadata, parts[2].lstrip()


def get_rules_source_files(src: Path) -> list[Path]:
    """读取全局规则源文件列表，支持 manifest 拼接和单文件兼容。"""
    if src.suffix.lower() != ".json":
        return [src]

    raw_config = json.loads(src.read_text(encoding="utf-8"))
    raw_rules = raw_config.get("rules") if isinstance(raw_config, dict) else raw_config
    if not isinstance(raw_rules, list):
        raise ValueError(f"{src.name}: rules 必须是数组")

    rule_files: list[Path] = []
    for index, raw_rule in enumerate(raw_rules, start=1):
        if isinstance(raw_rule, str):
            relative_path = raw_rule
        elif isinstance(raw_rule, dict):
            relative_path = str(raw_rule.get("path", "")).strip()
        else:
            raise ValueError(f"{src.name}: rules[{index}] 必须是字符串或对象")

        if not relative_path:
            raise ValueError(f"{src.name}: rules[{index}].path 不能为空")

        rule_file = (src.parent / relative_path).resolve()
        if not rule_file.exists():
            raise FileNotFoundError(f"{src.name}: 规则源文件不存在: {relative_path}")
        rule_files.append(rule_file)

    return rule_files


def build_rules_content(src: Path, strip_frontmatter: bool = False) -> str:
    """按规则清单拼接全局规则内容。"""
    parts: list[str] = []
    for index, rule_file in enumerate(get_rules_source_files(src)):
        text = rule_file.read_text(encoding="utf-8-sig")

        if index == 0 and not strip_frontmatter:
            parts.append(text.rstrip())
            continue

        _, body = split_frontmatter(text)
        parts.append(body.rstrip())

    return "\n\n".join(part for part in parts if part) + "\n"


def slugify(value: str) -> str:
    value = value.lower().replace(".", "-").replace("_", "-")
    value = re.sub(r"[^a-z0-9-]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value[:63] or "sky-workflow"


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def format_source_path(path: Path) -> str:
    """将生成来源路径格式化为仓库相对路径。"""
    resolved_path = path.resolve()
    try:
        return resolved_path.relative_to(ROOT).as_posix()
    except ValueError:
        return resolved_path.as_posix()


def is_generated_sky_workflow_skill(skill_text: str) -> bool:
    """判断 Skill 是否为本仓库工作流生成产物。"""
    if GENERATED_BY_MARKER in skill_text:
        return True

    return (
        SKY_WORKFLOW_DESCRIPTION_MARKER in skill_text
        and SOURCE_WORKFLOW_EDIT_MARKER in skill_text
    )


def iter_sync_source_files(src: Path, pattern: str, exclude: object = None) -> list[Path]:
    """按匹配规则获取源文件，并排除不参与同步的说明文件。"""
    excluded_names = set(as_list(exclude))
    return [src_file for src_file in sorted(src.glob(pattern)) if src_file.name not in excluded_names]


def is_same_file_content(left_file: Path, right_file: Path) -> bool:
    """判断两个文件内容是否一致，用于清理已排除的旧同步残留。"""
    try:
        return left_file.read_bytes() == right_file.read_bytes()
    except OSError:
        return False


def get_workflow_companion_target(item: dict[str, object]) -> Path | None:
    """获取工作流目标中的 project-catalog.json 伴随资源路径。"""
    src = item.get("src")
    if not isinstance(src, Path) or src.resolve() != SRC_WORKFLOWS.resolve():
        return None

    dst = item.get("dst")
    if not isinstance(dst, Path):
        raise ValueError(f"{item['name']}: 工作流目标路径无效")

    mode = str(item.get("mode", ""))
    if mode == "mirror":
        return dst / PROJECT_CATALOG_FILE.name

    if mode == "agents_skills":
        skill_name = slugify(PROJECT_CONTEXT_WORKFLOW_STEM)
        return dst / skill_name / PROJECT_CATALOG_FILE.name

    raise ValueError(f"{item['name']}: 工作流同步模式 {mode} 尚未支持伴随资源")


def get_workflow_skill_names(
    src: Path = SRC_WORKFLOWS,
    pattern: str = "*.md",
    exclude: object = None,
) -> list[str]:
    """获取 workflows 转换后的 Skill 目录名。"""
    if not src.exists():
        return []

    return [slugify(src_file.stem) for src_file in iter_sync_source_files(src, pattern, exclude or ["README.md"])]


def find_codex_cli() -> Path | None:
    """查找可执行的 Codex CLI，避免误用桌面入口 /usr/bin/codex。"""
    candidates: list[str | Path | None] = [
        shutil.which("codex-cli"),
        HOME / ".local" / "bin" / "codex-cli",
        Path("/usr/lib/codex/resources/codex"),
    ]

    for candidate in candidates:
        if not candidate:
            continue
        path = Path(candidate)
        if path.exists() and os.access(path, os.X_OK):
            return path

    return None


def run_codex_prompt_input_probe(expected_skill_names: list[str]) -> tuple[str, str]:
    """通过 Codex 自身 prompt-input 验证 Skills 是否进入模型可见上下文。"""
    codex_cli = find_codex_cli()
    if codex_cli is None:
        return "warn", "未找到 codex-cli，已跳过模型输入验证"

    try:
        result = subprocess.run(
            [str(codex_cli), "debug", "prompt-input", "sky-rules-sync-check"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        return "warn", f"prompt-input 验证未完成: {error}"

    if result.returncode != 0:
        message = (result.stderr or result.stdout).strip().splitlines()
        reason = message[0] if message else f"退出码 {result.returncode}"
        return "warn", f"prompt-input 验证失败: {reason}"

    probe_names = [name for name in expected_skill_names if name in {"base-debugging", "base-docs", "kl-gen-page"}]
    if not probe_names:
        probe_names = expected_skill_names[:3]

    missing = [name for name in probe_names if name not in result.stdout]
    if missing:
        return "fail", f"prompt-input 未看到 Skills: {', '.join(missing)}"

    return "ok", f"prompt-input 可见 Skills: {', '.join(probe_names)}"


def is_file_target(item: dict[str, object]) -> bool:
    """判断同步目标是否是单文件。"""
    return is_file_mode(str(item["mode"]))


def get_env_names(item: dict[str, object]) -> list[str]:
    """获取影响当前目标路径的环境变量名。"""
    return list(item.get("exact_env", [])) + list(item.get("base_env", []))


def has_target_env(item: dict[str, object]) -> bool:
    """判断当前目标是否由环境变量显式配置。"""
    return any(os.environ.get(env_name) for env_name in get_env_names(item))


def should_sync_target(item: dict[str, object], include_missing_targets: bool) -> bool:
    """判断目标是否应该同步。未检测到且未显式配置的工具默认跳过。"""
    if include_missing_targets:
        return True

    if has_target_env(item):
        return True

    detect_path = item.get("detect")
    if isinstance(detect_path, Path):
        return detect_path.exists()

    return True


def get_skip_reason(item: dict[str, object]) -> str:
    """生成未检测到工具时的跳过说明。"""
    detect_path = item.get("detect")
    if isinstance(detect_path, Path):
        return f"未检测到工具目录 ({detect_path})"

    return "未检测到工具目录"


def get_target_source(item: dict[str, object]) -> str:
    """获取目标路径来源：精确变量、根目录变量或默认路径。"""
    for env_name in item.get("exact_env", []):
        if os.environ.get(env_name):
            return f"{env_name}"

    for env_name in item.get("base_env", []):
        if os.environ.get(env_name):
            return f"{env_name} + 默认子路径"

    if item.get("config"):
        return f"{item['config']} 默认路径"

    return "默认路径"


def print_config_warnings() -> None:
    """输出扩展配置读取警告。"""
    if not CONFIG_WARNINGS:
        return

    print("[配置警告]")
    for warning in CONFIG_WARNINGS:
        print(f"  WARN {warning}")
    print()


def get_existing_parent(path: Path) -> Path | None:
    """查找离目标最近的已存在父目录。"""
    current_path = path
    while not current_path.exists():
        parent_path = current_path.parent
        if parent_path == current_path:
            return None
        current_path = parent_path

    if current_path.is_file():
        return current_path.parent

    return current_path


def check_directory_writable(directory: Path) -> tuple[bool, str]:
    """通过临时文件检测目录是否可写。"""
    test_file = directory / f".sky-rules-write-test-{os.getpid()}.tmp"
    try:
        test_file.write_text("test", encoding="utf-8")
        test_file.unlink()
    except OSError as error:
        return False, str(error)

    return True, "可写"


def diagnose_target(item: dict[str, object]) -> str:
    """体检单个同步目标，返回 ok / skip / fail。"""
    name = str(item["name"])
    dst = item["dst"]
    target_path = dst if isinstance(dst, Path) else Path(str(dst))
    target_type = "文件" if is_file_target(item) else "目录"
    target_container = target_path.parent if is_file_target(item) else target_path
    existing_parent = get_existing_parent(target_container)

    print(f"  [{name}]")
    print(f"    类型: {target_type}")
    print(f"    路径: {target_path}")
    print(f"    来源: {get_target_source(item)}")

    try:
        companion_target = get_workflow_companion_target(item)
    except ValueError as error:
        print(f"    伴随资源: FAIL {error}")
        return "fail"

    if companion_target is not None:
        print(f"    伴随资源: {companion_target}")

    if not should_sync_target(item, include_missing_targets=False):
        print(f"    检测: SKIP {get_skip_reason(item)}，默认同步会跳过")
        print("    提示: 如需同步到该工具，先启动工具生成目录、配置 SKY_RULES_*，或使用 --include-missing-targets")
        return "skip"

    if target_path.exists():
        print("    状态: 目标已存在")
    else:
        print("    状态: 目标不存在，同步时会创建")

    if existing_parent is None:
        print("    写入: FAIL 未找到可检查的父目录")
        return "fail"

    writable, message = check_directory_writable(existing_parent)
    if not writable:
        print(f"    写入: FAIL 最近父目录不可写 ({existing_parent})")
        print(f"    原因: {message}")
        return "fail"

    if existing_parent == target_container:
        print(f"    写入: OK {message}")
        return "ok"

    print(f"    写入: WARN 目标父目录未创建，最近父目录可写 ({existing_parent})")
    return "ok"


def sync_mirror(name: str, src: Path, dst: Path, pattern: str, exclude: object = None) -> None:
    """镜像同步：将源目录中匹配的文件完整同步到目标目录。"""
    if not src.exists():
        print(f"  SKIP {name}: 源目录不存在 ({src})")
        return

    dst.mkdir(parents=True, exist_ok=True)
    excluded_names = set(as_list(exclude))
    src_files = {f.name: f for f in iter_sync_source_files(src, pattern, excluded_names)}

    copied, skipped = 0, 0
    for name_f, src_file in src_files.items():
        dst_file = dst / name_f
        if dst_file.exists() and dst_file.stat().st_mtime >= src_file.stat().st_mtime:
            skipped += 1
            continue
        shutil.copy2(src_file, dst_file)
        copied += 1

    removed = 0
    for dst_file in dst.glob(pattern):
        if dst_file.name in excluded_names:
            excluded_src_file = src / dst_file.name
            if excluded_src_file.exists() and is_same_file_content(dst_file, excluded_src_file):
                dst_file.unlink()
                removed += 1
            continue
        if dst_file.name not in src_files:
            dst_file.unlink()
            removed += 1

    print(f"  OK {name}: 复制 {copied}, 跳过 {skipped}, 删除 {removed}")


def sync_file(name: str, src: Path, dst: Path) -> None:
    """单文件同步。"""
    if not src.exists():
        print(f"  SKIP {name}: 源文件不存在 ({src})")
        return

    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() and is_same_file_content(src, dst):
        print(f"  SKIP {name}: 无变更")
        return

    shutil.copy2(src, dst)
    print(f"  OK {name}: 已同步")


def sync_assembled_rules(name: str, src: Path, dst: Path, strip_frontmatter: bool = False) -> None:
    """拼接 rules manifest 中的规则文件并同步到单文件目标。"""
    if not src.exists():
        print(f"  SKIP {name}: 源文件不存在 ({src})")
        return

    content = build_rules_content(src, strip_frontmatter=strip_frontmatter)
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() and dst.read_text(encoding="utf-8", errors="replace") == content:
        print(f"  SKIP {name}: 无变更")
        return

    dst.write_text(content, encoding="utf-8", newline="\n")
    print(f"  OK {name}: 已同步")


def sync_codex_rules(name: str, src: Path, dst: Path) -> None:
    """同步全局规则到 Codex 的用户级 AGENTS.md。"""
    if not src.exists():
        print(f"  SKIP {name}: 源文件不存在 ({src})")
        return

    body = build_rules_content(src, strip_frontmatter=True)
    content = (
        f"<!-- {GENERATED_BY_MARKER}. Generated from {format_source_path(src)}. "
        "Edit the source files, then sync again. -->\n\n"
        f"{body.lstrip()}"
    )
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(content, encoding="utf-8", newline="\n")
    print(f"  OK {name}: 已同步")


def sync_agents_skills(name: str, src: Path, dst: Path, pattern: str, exclude: object = None) -> None:
    """将 workflows/*.md 转换为 Agents/Codex 可识别的 skill 目录。"""
    if not src.exists():
        print(f"  SKIP {name}: 源目录不存在 ({src})")
        return

    dst.mkdir(parents=True, exist_ok=True)
    source_names: set[str] = set()
    copied = 0

    for src_file in iter_sync_source_files(src, pattern, exclude):
        skill_name = slugify(src_file.stem)
        source_names.add(skill_name)

        text = src_file.read_text(encoding="utf-8")
        metadata, body = split_frontmatter(text)
        description = metadata.get("description") or src_file.stem
        description = f"Use when the user wants this Sky workflow: {description}"

        skill_dir = dst / skill_name
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_file = skill_dir / "SKILL.md"
        skill_file.write_text(
            "---\n"
            f"name: {skill_name}\n"
            f"description: {yaml_quote(description)}\n"
            "---\n\n"
            f"<!-- {GENERATED_BY_MARKER}. Generated from {format_source_path(src_file)}. "
            "Edit the source workflow, then sync again. -->\n\n"
            f"{body.rstrip()}\n",
            encoding="utf-8",
            newline="\n",
        )
        copied += 1

    removed = 0
    for skill_dir in dst.iterdir():
        if not skill_dir.is_dir():
            continue
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            continue
        try:
            skill_text = skill_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        generated = is_generated_sky_workflow_skill(skill_text)
        if generated and skill_dir.name not in source_names:
            shutil.rmtree(skill_dir)
            removed += 1

    print(f"  OK {name}: 生成 {copied}, 删除过期 {removed}")


def sync_workflow_companion(item: dict[str, object]) -> None:
    """同步与项目上下文工作流不可拆分的目录数据。"""
    companion_target = get_workflow_companion_target(item)
    if companion_target is None:
        return

    sync_file(
        f"{item['name']} 伴随资源",
        PROJECT_CATALOG_FILE,
        companion_target,
    )


def sync_all(include_missing_targets: bool = False) -> None:
    """执行全部同步任务。"""
    print_config_warnings()
    print("[2/2] 同步文件到各编辑器...")

    for item in SYNC_MAP:
        if not should_sync_target(item, include_missing_targets):
            print(f"  SKIP {item['name']}: {get_skip_reason(item)}")
            continue

        mode = item["mode"]
        if mode == "mirror":
            sync_mirror(item["name"], item["src"], item["dst"], item["pattern"], item.get("exclude"))
        elif mode == "file":
            sync_file(item["name"], item["src"], item["dst"])
        elif mode == "assembled_rules":
            sync_assembled_rules(item["name"], item["src"], item["dst"])
        elif mode == "codex_rules":
            sync_codex_rules(item["name"], item["src"], item["dst"])
        elif mode == "agents_skills":
            sync_agents_skills(item["name"], item["src"], item["dst"], item["pattern"], item.get("exclude"))

        sync_workflow_companion(item)


def verify_workflow_companions(include_missing_targets: bool = False) -> bool:
    """验证所有启用平台的项目目录伴随资源与源文件完全一致。"""
    print("[工作流伴随资源验证]")
    if not PROJECT_CATALOG_FILE.exists():
        print(f"  FAIL 源文件不存在: {PROJECT_CATALOG_FILE}")
        return False

    checked_count = 0
    failure_count = 0
    for item in SYNC_MAP:
        if not should_sync_target(item, include_missing_targets):
            continue

        try:
            companion_target = get_workflow_companion_target(item)
        except ValueError as error:
            print(f"  FAIL {error}")
            failure_count += 1
            continue

        if companion_target is None:
            continue

        checked_count += 1
        if not companion_target.exists():
            print(f"  FAIL {item['name']}: 缺少 {companion_target}")
            failure_count += 1
            continue

        if not is_same_file_content(PROJECT_CATALOG_FILE, companion_target):
            print(f"  FAIL {item['name']}: 内容与源文件不一致 ({companion_target})")
            failure_count += 1
            continue

        print(f"  OK {item['name']}: {companion_target}")

    if failure_count:
        print(f"  结论: FAIL，{failure_count} 个平台目标不一致")
        return False

    print(f"  结论: OK，{checked_count} 个平台目标与源文件一致")
    return True


def print_codex_verification() -> None:
    """输出 Codex 规则和 Skills 的落盘与加载验证结果。"""
    if not CODEX_HOME.exists():
        return

    print()
    print("[Codex 验证]")

    if CODEX_AGENTS_FILE.exists():
        rules_text = CODEX_AGENTS_FILE.read_text(encoding="utf-8", errors="replace")
        if GENERATED_BY_MARKER in rules_text:
            print(f"  OK 全局规则落盘: {CODEX_AGENTS_FILE}")
        else:
            print(f"  WARN 全局规则存在但不是 sky-rules 生成产物: {CODEX_AGENTS_FILE}")
    else:
        print(f"  FAIL 全局规则未落盘: {CODEX_AGENTS_FILE}")

    expected_skill_names = get_workflow_skill_names(exclude=["README.md"])
    missing_skill_names = [
        skill_name
        for skill_name in expected_skill_names
        if not (CODEX_SKILLS_DIR / skill_name / "SKILL.md").exists()
    ]

    if missing_skill_names:
        print(f"  FAIL Skills 缺失 {len(missing_skill_names)} 个: {', '.join(missing_skill_names[:5])}")
    else:
        print(f"  OK Skills 落盘: {len(expected_skill_names)} 个 -> {CODEX_SKILLS_DIR}")

    status, message = run_codex_prompt_input_probe(expected_skill_names)
    print(f"  {status.upper()} Skills 加载: {message}")


def print_sync_targets() -> None:
    """打印当前电脑解析到的同步目标。"""
    print("Sky Rules - 当前同步目标")
    print(f"  仓库根目录: {ROOT}")
    print(f"  用户目录: {HOME}")
    print()
    print_config_warnings()

    for item in SYNC_MAP:
        print(f"  {item['name']}: {item['dst']}")
        companion_target = get_workflow_companion_target(item)
        if companion_target is not None:
            print(f"    伴随资源: {companion_target}")


def run_doctor() -> None:
    """体检当前电脑同步配置。"""
    print("Sky Rules - 新电脑同步体检")
    print(f"  仓库根目录: {ROOT}")
    print(f"  用户目录: {HOME}")
    print()
    print_config_warnings()

    print("[源文件]")
    rules_file = RULES_MANIFEST
    try:
        rule_source_files = get_rules_source_files(rules_file)
        print(f"  OK 全局规则清单: {rules_file} ({len(rule_source_files)} 个源文件)")
    except (OSError, ValueError, FileNotFoundError, json.JSONDecodeError) as error:
        rule_source_files = []
        print(f"  FAIL 全局规则清单异常: {error}")

    if SRC_WORKFLOWS.exists():
        workflow_count = len(iter_sync_source_files(SRC_WORKFLOWS, "*.md", ["README.md"]))
        print(f"  OK 工作流目录: {SRC_WORKFLOWS} ({workflow_count} 个 .md)")
    else:
        workflow_count = 0
        print(f"  FAIL 工作流目录不存在: {SRC_WORKFLOWS}")

    if PROJECT_CATALOG_FILE.exists():
        print(f"  OK 项目目录源文件: {PROJECT_CATALOG_FILE}")
    else:
        print(f"  FAIL 项目目录源文件不存在: {PROJECT_CATALOG_FILE}")

    print()
    print("[目标路径]")
    target_results = [diagnose_target(item) for item in SYNC_MAP]

    config_ok = not CONFIG_WARNINGS
    source_ok = (
        bool(rule_source_files)
        and SRC_WORKFLOWS.exists()
        and workflow_count > 0
        and PROJECT_CATALOG_FILE.exists()
    )
    targets_ok = "fail" not in target_results
    skip_count = target_results.count("skip")
    print()
    print("[结论]")
    if config_ok and source_ok and targets_ok:
        print("  OK 当前电脑可以执行同步。")
        if skip_count:
            print(f"  提示: 检测到 {skip_count} 个未使用工具目标，默认同步会跳过。")
        print("  下一步: python sync-workflows.py --no-git")
        return

    print("  FAIL 当前电脑同步配置需要处理。")
    print("  建议: 先根据上方 FAIL/WARN 配置 SKY_RULES_* 环境变量，再重新运行 --doctor。")


def main() -> None:
    no_git = "--no-git" in sys.argv
    print_targets = "--print-targets" in sys.argv
    doctor = "--doctor" in sys.argv
    verify = "--verify" in sys.argv
    include_missing_targets = "--include-missing-targets" in sys.argv
    skip_rules_check = "--skip-rules-check" in sys.argv

    if print_targets:
        print_sync_targets()
        return

    if doctor:
        run_doctor()
        return

    if verify:
        print_config_warnings()
        if not verify_workflow_companions(include_missing_targets):
            raise SystemExit(1)
        return

    print("=" * 45)
    print("Sky Rules - 全量同步 (workflows + rules + skills)")
    print("=" * 45)
    print()

    if skip_rules_check:
        print("[规则自检] SKIP 已通过 --skip-rules-check 跳过内置自检")
        print()
    else:
        run_rules_check("同步前", source_only=True)

    update_local_source_config()
    print()

    if not no_git:
        git_commit_and_push()

    sync_all(include_missing_targets)
    if not verify_workflow_companions(include_missing_targets):
        raise SystemExit("工作流伴随资源验证失败，已阻断同步完成状态")
    print_codex_verification()

    if not skip_rules_check:
        print()
        run_rules_check("同步后")

    print()
    print("=" * 45)
    print("同步完成！重启编辑器/插件即可生效。")
    print("=" * 45)


if __name__ == "__main__":
    main()
