#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sky Rules 规则仓库自检脚本。"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
HOME = Path.home().resolve()

RULES_DIR = ROOT / "rules"
WORKFLOWS_DIR = ROOT / "workflows"
WORKFLOW_REFERENCES_DIR = WORKFLOWS_DIR / "references"
WORKFLOW_REFERENCE_SEPARATOR = "--"
MANIFEST_FILE = RULES_DIR / "rules-manifest.json"
PROJECT_CATALOG_FILE = ROOT / "project-catalog.json"

README_FILE = ROOT / "README.md"
AGENTS_FILE = ROOT / "AGENTS.md"
RULES_README_FILE = RULES_DIR / "README.md"
WORKFLOWS_README_FILE = WORKFLOWS_DIR / "README.md"
UPDATE_RULES_WORKFLOW = WORKFLOWS_DIR / "base.update-rules.md"
PROJECT_CONTEXT_WORKFLOW = WORKFLOWS_DIR / "base.project-context.md"
REQUIREMENT_DEV_CLOSED_LOOP_WORKFLOW = WORKFLOWS_DIR / "base.requirement-dev-closed-loop.md"
PINGCODE_FIX_BUG_WORKFLOW = WORKFLOWS_DIR / "base.pingcode-fix-bug.md"
KL_GEN_PAGE_WORKFLOW = WORKFLOWS_DIR / "kl.gen-page.md"
SYNC_SCRIPT = ROOT / "sync-workflows.py"
SYNC_TARGETS_EXAMPLE = ROOT / "sync-targets.example.json"

KL_GEN_PAGE_REFERENCE_NAMES = {
    "kl-gen-page--list-and-table.md",
    "kl-gen-page--forms-and-dialogs.md",
    "kl-gen-page--detail-and-navigation.md",
    "kl-gen-page--api-and-data.md",
    "kl-gen-page--components-and-display.md",
}

GENERATED_BY_MARKER = "Generated by sky-rules sync-workflows.py"
SOURCE_ONLY = "--source-only" in sys.argv

REQUIRED_ASSEMBLED_MARKERS = [
    "# 规则读取策略 / 场景索引",
    "## P0 硬性红线",
    "禁止跨接口借用字段",
    "# CSS/SCSS 样式规范",
    "# 联调开发规范",
    "## 跨接口字段归属规范",
    "# 后端接口契约与服务分层规范",
    "# 后端数据持久化与事务规范",
    "# 全栈测试、迁移与发布规范",
    "**AI 规则 / Skills 同步验证规范**",
    "## Element Plus Namespace 规范",
    "## 生效规则显性告知门禁",
]


class CheckState:
    """规则自检过程中的失败和警告收集器。"""

    def __init__(self) -> None:
        self.failures: list[str] = []
        self.warnings: list[str] = []

    def ok(self, message: str) -> None:
        print(f"OK   {message}")

    def warn(self, message: str) -> None:
        self.warnings.append(message)
        print(f"WARN {message}")

    def fail(self, message: str) -> None:
        self.failures.append(message)
        print(f"FAIL {message}")


STATE = CheckState()


def read_text(path: Path) -> str:
    """按 UTF-8 读取文本文件，兼容 BOM。"""
    return path.read_text(encoding="utf-8-sig")


def resolve_path(value: str | Path) -> Path:
    """解析环境变量和用户目录，用于定位同步产物。"""
    text = str(value)
    text = text.replace("${ROOT}", str(ROOT)).replace("${HOME}", str(HOME))
    return Path(os.path.expandvars(text)).expanduser().resolve()


def get_env_path(env_name: str, default: Path) -> Path:
    """读取路径环境变量；未配置时使用默认路径。"""
    value = os.environ.get(env_name)
    if not value:
        return default

    return resolve_path(value)


def get_first_env_path(env_names: list[str], default: Path) -> Path:
    """按优先级读取多个路径环境变量。"""
    for env_name in env_names:
        value = os.environ.get(env_name)
        if value:
            return resolve_path(value)

    return default


def get_codex_skills_dir(codex_home: Path) -> Path:
    """读取 Codex Skills 目录，兼容 Agents 旧变量。"""
    for env_name in ["SKY_RULES_CODEX_SKILLS_DIR", "SKY_RULES_AGENTS_SKILLS_DIR"]:
        value = os.environ.get(env_name)
        if value:
            return resolve_path(value)

    agents_home = os.environ.get("SKY_RULES_AGENTS_HOME")
    if agents_home:
        return resolve_path(agents_home) / "skills"

    return codex_home / "skills"


def assert_under(child: Path, parent: Path, message: str) -> bool:
    """确认路径没有逃出目标目录。"""
    try:
        child.relative_to(parent)
    except ValueError:
        STATE.fail(message)
        return False

    return True


def load_json(path: Path) -> Any:
    """读取 JSON 文件。"""
    try:
        return json.loads(read_text(path))
    except FileNotFoundError:
        STATE.fail(f"文件不存在: {path.relative_to(ROOT)}")
    except json.JSONDecodeError as error:
        STATE.fail(f"JSON 解析失败: {path.relative_to(ROOT)} ({error})")

    return None


def load_manifest_entries() -> list[dict[str, str]]:
    """读取并校验全局规则 manifest 基础结构。"""
    failure_count = len(STATE.failures)
    raw_manifest = load_json(MANIFEST_FILE)
    if not isinstance(raw_manifest, dict):
        STATE.fail("rules/rules-manifest.json 根节点必须是对象")
        return []

    raw_rules = raw_manifest.get("rules")
    if not isinstance(raw_rules, list) or not raw_rules:
        STATE.fail("rules/rules-manifest.json 的 rules 必须是非空数组")
        return []

    entries: list[dict[str, str]] = []
    seen_paths: set[str] = set()
    for index, raw_rule in enumerate(raw_rules, start=1):
        if not isinstance(raw_rule, dict):
            STATE.fail(f"rules[{index}] 必须是对象，需包含 path/title/description")
            continue

        path = str(raw_rule.get("path", "")).strip()
        title = str(raw_rule.get("title", "")).strip()
        description = str(raw_rule.get("description", "")).strip()

        if not path:
            STATE.fail(f"rules[{index}].path 不能为空")
            continue
        if not title:
            STATE.fail(f"{path}: title 不能为空")
        if not description:
            STATE.fail(f"{path}: description 不能为空")
        if path in seen_paths:
            STATE.fail(f"manifest 路径重复: {path}")
            continue

        seen_paths.add(path)
        rule_file = (RULES_DIR / path).resolve()
        if not assert_under(rule_file, RULES_DIR, f"manifest 路径逃出 rules 目录: {path}"):
            continue
        if not rule_file.exists():
            STATE.fail(f"manifest 指向的规则文件不存在: {path}")
            continue
        if rule_file.suffix.lower() != ".md":
            STATE.fail(f"manifest 只能引用 Markdown 规则文件: {path}")
            continue

        entries.append(
            {
                "path": path,
                "title": title,
                "description": description,
            }
        )

    if entries and entries[0]["path"] != "global-rules.md":
        STATE.fail("manifest 第一项必须是 global-rules.md，确保 P0 红线优先进入上下文")

    if entries and len(STATE.failures) == failure_count:
        STATE.ok(f"manifest 基础结构正常，共 {len(entries)} 个规则源文件")

    return entries


def check_project_catalog() -> None:
    """确认项目文档目录遵循一来源一条目结构。"""
    failure_count = len(STATE.failures)
    raw_catalog = load_json(PROJECT_CATALOG_FILE)
    if not isinstance(raw_catalog, dict):
        STATE.fail("project-catalog.json 根节点必须是对象")
        return

    extra_root_keys = sorted(set(raw_catalog) - {"projects"})
    if extra_root_keys:
        STATE.fail(
            "project-catalog.json 根节点只允许 projects，禁止新增字段: "
            + ", ".join(extra_root_keys)
        )

    raw_projects = raw_catalog.get("projects")
    if not isinstance(raw_projects, list) or not raw_projects:
        STATE.fail("project-catalog.json 的 projects 必须是非空数组")
        return

    allowed_project_keys = {"project", "description", "match", "docs", "rules"}
    seen_projects: set[str] = set()
    for index, raw_project in enumerate(raw_projects, start=1):
        prefix = f"project-catalog.json projects[{index}]"
        if not isinstance(raw_project, dict):
            STATE.fail(f"{prefix} 必须是对象")
            continue

        missing_project_keys = sorted(allowed_project_keys - set(raw_project))
        if missing_project_keys:
            STATE.fail(f"{prefix} 缺少模板字段: {', '.join(missing_project_keys)}")

        extra_project_keys = sorted(set(raw_project) - allowed_project_keys)
        if extra_project_keys:
            STATE.fail(
                f"{prefix} 只允许 project/description/match/docs/rules，禁止新增字段: "
                + ", ".join(extra_project_keys)
            )

        project = str(raw_project.get("project", "")).strip()
        description = str(raw_project.get("description", "")).strip()
        docs = raw_project.get("docs")

        if not project:
            STATE.fail(f"{prefix}.project 不能为空")
        elif project in seen_projects:
            STATE.fail(f"project-catalog.json project 重复: {project}")
        else:
            seen_projects.add(project)

        if not description:
            STATE.fail(f"{prefix}.description 不能为空")

        if not isinstance(docs, str) or not docs.strip():
            STATE.fail(f"{prefix}.docs 必须是单一本地 / Git 相对目录或 HTTPS URL 字符串")
        else:
            docs = docs.strip()
            if docs.startswith("http://"):
                STATE.fail(f"{prefix}.docs 网页文档必须使用 HTTPS: {docs}")
            elif not docs.startswith("https://") and Path(docs).is_absolute():
                STATE.fail(f"{prefix}.docs 禁止保存绝对路径: {docs}")

        for key in ["match", "rules"]:
            values = raw_project.get(key, [])
            if not isinstance(values, list) or any(
                not isinstance(value, str) or not value.strip()
                for value in values
            ):
                STATE.fail(f"{prefix}.{key} 必须是字符串数组")

    if len(STATE.failures) == failure_count:
        STATE.ok(f"project-catalog.json 结构正常，共 {len(raw_projects)} 个独立文档来源")


def slugify_workflow_name(value: str) -> str:
    """按同步脚本规则生成工作流对应的 Skill 名称。"""
    value = value.lower().replace(".", "-").replace("_", "-")
    value = re.sub(r"[^a-z0-9-]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value[:63] or "sky-workflow"


def check_workflow_references() -> None:
    """检查渐进式工作流引用的归属、链接和 kl-gen-page 主入口体量。"""
    failure_count = len(STATE.failures)
    workflow_files = sorted(
        workflow_file
        for workflow_file in WORKFLOWS_DIR.glob("*.md")
        if workflow_file.name != "README.md"
    )
    workflow_by_skill_name: dict[str, Path] = {}
    for workflow_file in workflow_files:
        skill_name = slugify_workflow_name(workflow_file.stem)
        if skill_name in workflow_by_skill_name:
            STATE.fail(
                "工作流转换后的 Skill 名称重复: "
                f"{workflow_by_skill_name[skill_name].name}, {workflow_file.name} -> {skill_name}"
            )
            continue
        workflow_by_skill_name[skill_name] = workflow_file

    reference_files = sorted(WORKFLOW_REFERENCES_DIR.glob("*.md")) if WORKFLOW_REFERENCES_DIR.exists() else []
    reference_names = {reference_file.name for reference_file in reference_files}
    references_by_owner: dict[str, set[str]] = {}

    for reference_file in reference_files:
        owner_name, separator, topic = reference_file.stem.partition(WORKFLOW_REFERENCE_SEPARATOR)
        if not separator or not owner_name or not topic:
            STATE.fail(
                "工作流引用命名不符合 <skill-name>--<topic>.md: "
                f"{reference_file.relative_to(ROOT).as_posix()}"
            )
            continue
        if owner_name not in workflow_by_skill_name:
            STATE.fail(f"工作流引用缺少归属工作流: {reference_file.name} -> {owner_name}")
            continue

        references_by_owner.setdefault(owner_name, set()).add(reference_file.name)
        workflow_text = read_text(workflow_by_skill_name[owner_name])
        expected_link = f"references/{reference_file.name}"
        if expected_link not in workflow_text:
            STATE.fail(f"工作流引用未从主工作流链接: {reference_file.name}")

    for skill_name, workflow_file in workflow_by_skill_name.items():
        workflow_text = read_text(workflow_file)
        linked_names = set(
            re.findall(
                r"references/([a-z0-9][a-z0-9-]*--[a-z0-9][a-z0-9-]*\.md)",
                workflow_text,
            )
        )
        for linked_name in sorted(linked_names):
            if linked_name not in reference_names:
                STATE.fail(f"主工作流链接的引用不存在: {workflow_file.name} -> {linked_name}")
                continue
            if not linked_name.startswith(f"{skill_name}{WORKFLOW_REFERENCE_SEPARATOR}"):
                STATE.fail(f"主工作流跨归属引用资源: {workflow_file.name} -> {linked_name}")

    kl_gen_page_text = read_text(KL_GEN_PAGE_WORKFLOW)
    kl_gen_page_reference_names = references_by_owner.get("kl-gen-page", set())
    missing_kl_references = sorted(KL_GEN_PAGE_REFERENCE_NAMES - kl_gen_page_reference_names)
    extra_kl_references = sorted(kl_gen_page_reference_names - KL_GEN_PAGE_REFERENCE_NAMES)
    if missing_kl_references:
        STATE.fail(f"kl.gen-page.md 缺少引用资源: {', '.join(missing_kl_references)}")
    if extra_kl_references:
        STATE.fail(f"kl.gen-page.md 存在未登记引用资源: {', '.join(extra_kl_references)}")

    kl_gen_page_line_count = len(kl_gen_page_text.splitlines())
    if kl_gen_page_line_count >= 180:
        STATE.fail(f"kl.gen-page.md 主入口过长: {kl_gen_page_line_count} 行，应继续拆入 references")

    if re.search(r"[A-Za-z]:[\\/]", kl_gen_page_text):
        STATE.fail("kl.gen-page.md 禁止包含本机绝对路径")

    forbidden_kl_markers = ["Promise.resolve({ data: { records", "fnApi: () => Promise.resolve", "as any"]
    matched_forbidden_markers = [marker for marker in forbidden_kl_markers if marker in kl_gen_page_text]
    if matched_forbidden_markers:
        STATE.fail(f"kl.gen-page.md 仍包含组件内 Mock 或类型兜底: {', '.join(matched_forbidden_markers)}")

    required_kl_markers = [
        "## 0. 核心不变量",
        "## 2. 按场景读取引用资料",
        "只读取当前任务命中的引用文件",
        "项目源码不一致",
        "## 5. 交付前检查",
    ]
    missing_kl_markers = [marker for marker in required_kl_markers if marker not in kl_gen_page_text]
    if missing_kl_markers:
        STATE.fail(f"kl.gen-page.md 缺少渐进式入口约束: {', '.join(missing_kl_markers)}")

    if len(STATE.failures) == failure_count:
        STATE.ok(
            "工作流引用归属、链接和 kl-gen-page 渐进式入口正常，"
            f"共 {len(reference_files)} 个引用资源"
        )


def get_manifest_paths(entries: list[dict[str, str]]) -> set[str]:
    """获取 manifest 中的规则相对路径集合。"""
    return {entry["path"] for entry in entries}


def check_rule_files_are_listed(entries: list[dict[str, str]]) -> None:
    """确认拆分目录下的规则文件都进入 manifest。"""
    manifest_paths = get_manifest_paths(entries)
    expected_paths: set[str] = {"global-rules.md"}

    for directory_name in ["common", "frontend", "backend", "projects"]:
        directory = RULES_DIR / directory_name
        if not directory.exists():
            STATE.warn(f"规则目录不存在: rules/{directory_name}")
            continue

        for rule_file in sorted(directory.glob("*.md")):
            expected_paths.add(rule_file.relative_to(RULES_DIR).as_posix())

    missing_paths = sorted(expected_paths - manifest_paths)
    extra_paths = sorted(manifest_paths - expected_paths)

    if missing_paths:
        STATE.fail(f"规则文件未加入 manifest: {', '.join(missing_paths)}")

    if extra_paths:
        STATE.fail(f"manifest 引用了非标准规则源文件: {', '.join(extra_paths)}")

    if not missing_paths and not extra_paths:
        STATE.ok("rules/common、rules/frontend、rules/backend、rules/projects 下的规则文件均已进入 manifest")


def check_index_files(entries: list[dict[str, str]]) -> None:
    """确认维护索引能指向关键结构和规则源文件。"""
    rules_readme = read_text(RULES_README_FILE)
    workflows_readme = read_text(WORKFLOWS_README_FILE)
    root_readme = read_text(README_FILE)
    agents = read_text(AGENTS_FILE)
    update_rules_workflow = read_text(UPDATE_RULES_WORKFLOW)
    project_context_workflow = read_text(PROJECT_CONTEXT_WORKFLOW)
    requirement_dev_closed_loop_workflow = read_text(REQUIREMENT_DEV_CLOSED_LOOP_WORKFLOW)
    pingcode_fix_bug_workflow = read_text(PINGCODE_FIX_BUG_WORKFLOW)

    missing_from_rules_readme = [
        entry["path"]
        for entry in entries
        if entry["path"] not in rules_readme
    ]
    if missing_from_rules_readme:
        STATE.fail(f"rules/README.md 缺少规则文件索引: {', '.join(missing_from_rules_readme)}")
    else:
        STATE.ok("rules/README.md 已覆盖 manifest 中的全部规则源文件")

    required_root_readme_markers = [
        "rules/rules-manifest.json",
        "rules/common/",
        "rules/frontend/",
        "rules/backend/",
        "assembled_rules",
        "codex_rules",
        "scripts/check-rules.py",
        "project-catalog.json",
        "workflows/references/",
        "<skill-name>--<topic>.md",
        "工作流资源包",
        "--verify",
        "闭环验收回执",
        "内置自检",
        "--skip-rules-check",
        "规则质量自审",
    ]
    missing_root_readme_markers = [
        marker
        for marker in required_root_readme_markers
        if marker not in root_readme
    ]
    if missing_root_readme_markers:
        STATE.fail(f"README.md 缺少维护闭环说明: {', '.join(missing_root_readme_markers)}")
    else:
        STATE.ok("README.md 已说明 manifest、工作流资源包和自检入口")

    required_workflows_readme_markers = [
        "工作流伴随资源",
        "工作流渐进式引用",
        "<skill-name>--<topic>.md",
        "project-catalog.json",
        "mirror",
        "agents_skills",
        "一致性验证必须失败",
    ]
    missing_workflows_readme_markers = [
        marker
        for marker in required_workflows_readme_markers
        if marker not in workflows_readme
    ]
    if missing_workflows_readme_markers:
        STATE.fail(
            "workflows/README.md 缺少伴随资源维护约束: "
            + ", ".join(missing_workflows_readme_markers)
        )
    else:
        STATE.ok("workflows/README.md 已说明跨平台工作流伴随资源约束")

    required_agents_markers = [
        "rules/README.md",
        "rules/rules-manifest.json",
        "rules/common/",
        "rules/frontend/",
        "rules/backend/",
        "scripts/check-rules.py",
        "project-catalog.json",
        "workflows/references/",
        "闭环验收回执",
        "内置自检",
        "--skip-rules-check",
        "规则质量自审",
    ]
    missing_agents_markers = [
        marker
        for marker in required_agents_markers
        if marker not in agents
    ]
    if missing_agents_markers:
        STATE.fail(f"AGENTS.md 缺少 AI 维护入口说明: {', '.join(missing_agents_markers)}")
    else:
        STATE.ok("AGENTS.md 已包含规则索引、manifest 和自检入口")

    required_update_rules_markers = [
        "全局规则拆分文件定位规范",
        "rules/rules-manifest.json",
        "rules/common/",
        "rules/frontend/",
        "rules/backend/",
        "scripts/check-rules.py",
        "闭环验收结果",
        "内置自检",
        "--skip-rules-check",
        "规则抽象、演进与可见性自审门禁",
        "规则质量不得依赖用户在预览中发现问题",
        "未来扩展反向审计",
        "工作流渐进式拆分规范",
        "<skill-name>--<topic>.md",
    ]
    missing_update_rules_markers = [
        marker
        for marker in required_update_rules_markers
        if marker not in update_rules_workflow
    ]
    if missing_update_rules_markers:
        STATE.fail(f"base.update-rules.md 缺少规则维护闭环: {', '.join(missing_update_rules_markers)}")
    else:
        STATE.ok("base.update-rules.md 已串联拆分定位、manifest 和自检入口")

    required_project_context_markers = [
        "一来源一条目",
        "固定模板字段",
        "project-catalog.json",
        "多平台一致性",
        "工作流文件或 Skill 文件同目录",
        "https://",
        "git fetch origin main",
        "禁止默认选择或跨环境借用字段",
    ]
    missing_project_context_markers = [
        marker
        for marker in required_project_context_markers
        if marker not in project_context_workflow
    ]
    if missing_project_context_markers:
        STATE.fail(
            "base.project-context.md 缺少多来源目录读取约束: "
            + ", ".join(missing_project_context_markers)
        )
    else:
        STATE.ok("base.project-context.md 已覆盖一来源一条目、Git 和网页文档读取")

    required_requirement_closed_loop_markers = [
        "当前开发范围：前端 / 后端 / 全栈",
        "阶段 6：实现方案设计",
        "数据模型与 Migration",
        "测试策略",
        "发布顺序与回滚方案",
        "AI 能力发散审计",
        "业务对象、生命周期、角色、范围和跨系统关系",
        "定位、聚合、关联、诊断、建议、执行、持续能力和组合任务",
        "同领域定位、详情、关系和只读工具",
        "能力对等",
        "合理能力发散不得越过接口、字段、权限、枚举和写操作确认红线",
        "能力发散审计结论",
    ]
    missing_requirement_closed_loop_markers = [
        marker
        for marker in required_requirement_closed_loop_markers
        if marker not in requirement_dev_closed_loop_workflow
    ]
    if missing_requirement_closed_loop_markers:
        STATE.fail(
            "base.requirement-dev-closed-loop.md 缺少全栈开发与 AI 能力发散审计闭环: "
            + ", ".join(missing_requirement_closed_loop_markers)
        )
    else:
        STATE.ok("base.requirement-dev-closed-loop.md 已覆盖全栈开发、AI 能力发散审计与验收闭环")

    required_pingcode_fix_bug_markers = [
        "allow_implicit_invocation: false",
        "仅当用户显式调用 `$base-pingcode-fix-bug`",
        "不构成触发条件",
    ]
    missing_pingcode_fix_bug_markers = [
        marker
        for marker in required_pingcode_fix_bug_markers
        if marker not in pingcode_fix_bug_workflow
    ]
    if missing_pingcode_fix_bug_markers:
        STATE.fail(
            "base.pingcode-fix-bug.md 缺少仅显式调用约束: "
            + ", ".join(missing_pingcode_fix_bug_markers)
        )
    else:
        STATE.ok("base.pingcode-fix-bug.md 已限制为用户显式调用")


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """拆分 Markdown frontmatter，和同步脚本保持一致。"""
    text = text.lstrip("\ufeff")
    if not text.startswith("---"):
        return {}, text

    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text

    metadata: dict[str, str] = {}
    for line in parts[1].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip().strip('"').strip("'")

    return metadata, parts[2].lstrip()


def assemble_rules(entries: list[dict[str, str]], strip_frontmatter: bool = False) -> str:
    """按 manifest 拼接全局规则，用于校验同步脚本的关键产物。"""
    parts: list[str] = []
    for index, entry in enumerate(entries):
        rule_file = RULES_DIR / entry["path"]
        text = read_text(rule_file)

        if index == 0 and not strip_frontmatter:
            parts.append(text.rstrip())
            continue

        _, body = split_frontmatter(text)
        parts.append(body.rstrip())

    return "\n\n".join(part for part in parts if part) + "\n"


def check_assembled_rules(entries: list[dict[str, str]]) -> None:
    """确认拼接后的规则仍包含关键红线和场景细则。"""
    assembled_rules = assemble_rules(entries)
    missing_markers = [
        marker
        for marker in REQUIRED_ASSEMBLED_MARKERS
        if marker not in assembled_rules
    ]

    if missing_markers:
        STATE.fail(f"拼接后的全局规则缺少关键内容: {', '.join(missing_markers)}")
    else:
        STATE.ok("拼接后的全局规则包含 P0、前端样式、联调、跨接口、后端、全栈测试发布和同步验证关键规则")

    codex_rules = assemble_rules(entries, strip_frontmatter=True).lstrip()
    if codex_rules.startswith("---"):
        STATE.fail("Codex 全局规则拼接结果仍包含 frontmatter")
    else:
        STATE.ok("Codex 全局规则拼接结果已去除 frontmatter")


def check_sync_script() -> None:
    """确认同步脚本仍支持 manifest 拼接和 README 排除。"""
    script = read_text(SYNC_SCRIPT)
    required_script_markers = [
        "RULES_MANIFEST",
        "CHECK_RULES_SCRIPT",
        "assembled_rules",
        "codex_rules",
        "build_rules_content",
        "run_rules_check",
        "PROJECT_CATALOG_FILE",
        "WORKFLOW_REFERENCES_DIR_NAME",
        "get_workflow_companion_target",
        "get_workflow_reference_groups",
        "sync_workflow_companion",
        "sync_workflow_references",
        "verify_workflow_companions",
        "--verify",
        "--skip-rules-check",
        "--source-only",
        '"exclude": ["README.md"]',
        "allow_implicit_invocation",
        "openai.yaml",
    ]
    missing_script_markers = [
        marker
        for marker in required_script_markers
        if marker not in script
    ]

    if missing_script_markers:
        STATE.fail(f"sync-workflows.py 缺少关键同步能力: {', '.join(missing_script_markers)}")
    else:
        STATE.ok("sync-workflows.py 已支持规则拼接、工作流引用资源同步验证和 README 排除")


def check_sync_targets_example() -> None:
    """确认同步目标配置示例仍可被解析。"""
    failure_count = len(STATE.failures)
    raw_config = load_json(SYNC_TARGETS_EXAMPLE)
    if not isinstance(raw_config, dict):
        STATE.fail("sync-targets.example.json 根节点必须是对象")
        return

    raw_targets = raw_config.get("targets")
    if not isinstance(raw_targets, list) or not raw_targets:
        STATE.fail("sync-targets.example.json 必须包含非空 targets 数组")
        return

    for index, raw_target in enumerate(raw_targets, start=1):
        if not isinstance(raw_target, dict):
            STATE.fail(f"sync-targets.example.json targets[{index}] 必须是对象")
            continue

        for key in ["name", "mode", "source", "target"]:
            if not raw_target.get(key):
                STATE.fail(f"sync-targets.example.json targets[{index}].{key} 不能为空")

        mode = raw_target.get("mode")
        if mode not in {"mirror", "file", "assembled_rules", "codex_rules", "agents_skills"}:
            STATE.fail(f"sync-targets.example.json targets[{index}] mode 不支持: {mode}")

    if len(STATE.failures) == failure_count:
        STATE.ok(f"sync-targets.example.json 可解析，共 {len(raw_targets)} 个示例目标")


def check_generated_outputs() -> None:
    """检查已生成的同步产物是否暴露了关键维护规则。"""
    try:
        companion_result = subprocess.run(
            [sys.executable, str(SYNC_SCRIPT), "--verify"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        STATE.fail(f"工作流伴随资源验证未完成: {error}")
    else:
        companion_output = (companion_result.stdout or companion_result.stderr).strip()
        if companion_result.returncode != 0:
            STATE.fail("工作流伴随资源跨平台验证失败: " + companion_output.replace("\n", " | "))
        else:
            STATE.ok("所有启用平台的 project-catalog.json 和工作流引用资源与源文件一致")

    codex_home = get_first_env_path(["SKY_RULES_CODEX_HOME", "CODEX_HOME"], HOME / ".codex")
    codex_skills_dir = get_codex_skills_dir(codex_home)
    codex_update_rules_skill = codex_skills_dir / "base-update-rules" / "SKILL.md"
    codex_kl_gen_page_dir = codex_skills_dir / "kl-gen-page"
    codex_kl_gen_page_skill = codex_kl_gen_page_dir / "SKILL.md"
    codex_pingcode_fix_bug_policy = codex_skills_dir / "base-pingcode-fix-bug" / "agents" / "openai.yaml"
    codex_readme_skill = codex_skills_dir / "readme" / "SKILL.md"

    if codex_update_rules_skill.exists():
        skill_text = read_text(codex_update_rules_skill)
        missing_skill_markers = [
            marker
            for marker in [
                "全局规则拆分文件定位规范",
                "规则抽象、演进与可见性自审门禁",
                "规则质量不得依赖用户在预览中发现问题",
                "rules/rules-manifest.json",
                "scripts/check-rules.py",
                "闭环验收结果",
            ]
            if marker not in skill_text
        ]
        if missing_skill_markers:
            if codex_update_rules_skill.stat().st_mtime < UPDATE_RULES_WORKFLOW.stat().st_mtime:
                STATE.warn(
                    "Codex base-update-rules Skill 旧于源工作流，同步后应包含维护闭环: "
                    + ", ".join(missing_skill_markers)
                )
            else:
                STATE.fail(f"Codex base-update-rules Skill 尚未包含维护闭环: {', '.join(missing_skill_markers)}")
        else:
            STATE.ok("Codex base-update-rules Skill 已包含拆分定位、manifest 和自检入口")
    else:
        STATE.warn("未找到 Codex base-update-rules Skill；同步后会再次检查")

    if codex_kl_gen_page_skill.exists():
        kl_skill_failure_count = len(STATE.failures)
        kl_skill_text = read_text(codex_kl_gen_page_skill)
        if len(kl_skill_text.splitlines()) >= 190:
            STATE.fail("Codex kl-gen-page/SKILL.md 仍然过长，渐进式拆分未生效")

        missing_reference_links = [
            reference_name
            for reference_name in sorted(KL_GEN_PAGE_REFERENCE_NAMES)
            if f"references/{reference_name}" not in kl_skill_text
        ]
        if missing_reference_links:
            STATE.fail(f"Codex kl-gen-page/SKILL.md 缺少引用链接: {', '.join(missing_reference_links)}")

        codex_reference_dir = codex_kl_gen_page_dir / "references"
        missing_reference_files = [
            reference_name
            for reference_name in sorted(KL_GEN_PAGE_REFERENCE_NAMES)
            if not (codex_reference_dir / reference_name).exists()
        ]
        if missing_reference_files:
            STATE.fail(f"Codex kl-gen-page 缺少引用资源: {', '.join(missing_reference_files)}")

        if len(STATE.failures) == kl_skill_failure_count:
            STATE.ok("Codex kl-gen-page 已使用精简主入口并落盘 5 个按需引用资源")
    else:
        STATE.warn("未找到 Codex kl-gen-page Skill；同步后会再次检查")

    if codex_pingcode_fix_bug_policy.exists():
        policy_text = read_text(codex_pingcode_fix_bug_policy)
        if "allow_implicit_invocation: false" in policy_text:
            STATE.ok("Codex base-pingcode-fix-bug Skill 已限制为仅显式调用")
        else:
            STATE.fail("Codex base-pingcode-fix-bug Skill 调用策略不是 allow_implicit_invocation: false")
    else:
        STATE.fail("未找到 Codex base-pingcode-fix-bug Skill 显式调用策略")

    if codex_readme_skill.exists():
        skill_text = read_text(codex_readme_skill)
        if GENERATED_BY_MARKER in skill_text or "Generated from workflows/README.md" in skill_text:
            STATE.fail("Codex Skills 中存在由 workflows/README.md 生成的 readme Skill，应由同步排除清理")
        else:
            STATE.warn("Codex Skills 中存在 readme/SKILL.md，但不是 sky-rules 生成产物，请人工确认是否保留")
    else:
        STATE.ok("Codex Skills 未生成 workflows/README.md 对应的 readme Skill")

    windsurf_home = get_env_path("SKY_RULES_WINDSURF_HOME", HOME / ".codeium" / "windsurf")
    gemini_home = get_env_path("SKY_RULES_GEMINI_HOME", HOME / ".gemini")
    workflow_readme_targets = [
        get_env_path("SKY_RULES_WINDSURF_WORKFLOWS_DIR", windsurf_home / "global_workflows") / "README.md",
        get_env_path("SKY_RULES_GEMINI_WORKFLOWS_DIR", gemini_home / "antigravity" / "global_workflows") / "README.md",
    ]

    source_workflows_readme = read_text(WORKFLOWS_DIR / "README.md")
    for target_file in workflow_readme_targets:
        if not target_file.exists():
            STATE.ok(f"工作流同步目录未残留 README.md: {target_file}")
            continue

        target_text = read_text(target_file)
        if target_text == source_workflows_readme:
            STATE.fail(f"工作流同步目录残留 workflows/README.md: {target_file}")
        else:
            STATE.warn(f"工作流同步目录存在 README.md，但内容不是源 README，请人工确认: {target_file}")


def main() -> int:
    print("Sky Rules - 规则仓库自检")
    print(f"仓库根目录: {ROOT}")
    if SOURCE_ONLY:
        print("检查模式: source-only，仅检查源规则、索引和同步脚本能力")
    print()

    entries = load_manifest_entries()
    check_project_catalog()
    check_workflow_references()
    if entries:
        check_rule_files_are_listed(entries)
        check_index_files(entries)
        check_assembled_rules(entries)

    check_sync_script()
    check_sync_targets_example()
    if SOURCE_ONLY:
        STATE.ok("source-only 模式已跳过同步产物检查")
    else:
        check_generated_outputs()

    print()
    if STATE.failures:
        print(f"结论: FAIL，发现 {len(STATE.failures)} 个失败项、{len(STATE.warnings)} 个警告项")
        return 1

    if STATE.warnings:
        print(f"结论: OK_WITH_WARNINGS，发现 {len(STATE.warnings)} 个警告项")
        return 0

    if SOURCE_ONLY:
        print("结论: OK，规则结构、索引、自检入口和同步脚本能力检查通过")
        return 0

    print("结论: OK，规则结构、索引、自检入口和同步产物检查通过")
    return 0


if __name__ == "__main__":
    sys.exit(main())
